server.port: 7003
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/cart-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000



logging:
  level:
    root: INFO
    fab.shop: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080
